# Generated by Django 4.1.5 on 2023-01-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendees', to='events.attendance'),
            preserve_default=False,
        ),
    ]
