# Generated by Django 4.1.5 on 2023-01-28 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_event_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendee',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
