# Generated by Django 4.1.5 on 2023-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('online', models.BooleanField()),
                ('is_open', models.BooleanField(default=True)),
                ('image', models.URLField()),
                ('min_attendees', models.IntegerField()),
                ('max_attendees', models.IntegerField()),
                ('owner_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Pledge',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
