# Generated by Django 4.1.5 on 2023-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_event_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
