# Generated by Django 4.1.5 on 2023-01-22 01:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_attendance_remove_event_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.event'),
        ),
    ]
